spring.application.name=3_SPRING

# context path 설정(3번째 레벨 패키지명과 맞추기)
server.servlet.context-path=/spring

# prot 번호 설정(생략시 8080으로 잡힘, 오라클이 쓰고있으므로 8888로 변경)
server.port=8888

#view resolver 설정(접두어 : 폴더경로, 접미어 : 파일 확장자명)
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp