# properties 파일의 주석

# * application.properties 파일
# - 이 웹 프로젝트 구동 시 필요한 설정들, 연동된 라이브러리들로부터 필요한 코드 설정 등을 적는 파일
# - 키=밸류 형식으로 한 줄 단위로 적는다.

# 이 프로젝트의 이름 (기본 설정)
spring.application.name=1_Web

# 지금부터 이 아래에 내가 필요한 설정 값들을 적어주면 됨!!

# 이 웹사이트 구동 시 필요한 설정값들
# 1. context path 지정하기 : 메인화면을 나타내는 url 주소 (context root 라고도 부름)
# (주로 3번째 레벨의 패키지명으로 맞춰서 작성한다)
server.servlet.context-path=/web

# 2. 이 웹사이트 구동 시 필요한 포트번호 지정하기 : 반드시 사용되지 않는 (중복되지 않는) 번호로 지정할 것
server.port=8888
# - 이 설정은 생략 가능하다!! 단, 생략하는 순간 기본적으로 포트번호가 8080 번으로 잡히게 된다!!
# - 8080 포트번호는 이미 오라클이 사용하고 있어서 충돌남!! (반드시 내가 직접 다른 번호로 지정하는 습관 들이기)

# 우리 웹 사이트의 메인페이지 url 주소
# http://localhost:8888/web

# 분명히 jsp 를 사용하기 위한 라이브러리도 연동했고, 제대로된 경로에 index.jsp 파일도 만들어뒀음!!
# - 그럼에도 불구하고 위의 url 주소로 접속했더니 오류 화면이 나오는 것을 볼 수 있다!!
# - 화면 관련 파일들이 어느 경로에 있는지 설정이 아직 안되서 오류가 발생하는 것임!!

# 3. 화면 관련 파일 경로 완성 설정 : View Resolver 설정
# - 아까 화면 관련된 파일들을 src/main 폴더의 webapp 폴더 안쪽에 WEB-INF/views 폴더 안쪽에 만들었었음!!
# - 파일의 확장자 (파일의 종류) 는 .jsp 였음!!
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
# - prefix : 접두어, suffix : 접미어






