# 프로젝트명
spring.application.name=2_JSP

# context path : 이 웹 사이트의 메인 url 주소를 나타내는 부분 (주로 3번째 레벨 패키지명과 맞춰줌)
server.servlet.context-path=/jsp

# port 번호 : 안쓰면 기본적으로 8080 으로 잡힘!! (오라클에서 이미 사용중이여서 직접 지정하기)
server.port=8888
# 기존에 쓰던 1_Web 도 8888 번임!! 동시에 두개의 프로젝트를 구동시킬 수 없다!!
# (한번에 하나씩만 구동시켜야함)

# 우리의 메인페이지 주소는
# http://localhost:8888/jsp

# View Resolver 설정 : 화면 경로 자동완성 설정
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
